array_width = 60
attr_fn_like_width = 70
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 60
color = "Auto"
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
doc_comment_code_block_width = 80
edition = "2021"
emit_mode = "Files"
empty_item_single_line = true
enum_discrim_align_threshold = 40
error_on_line_overflow = false
error_on_unformatted = false
fn_call_width = 60
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
generated_marker_line_search_limit = 5
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Lower"
ignore = []
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
make_backup = false
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
required_version = "1.8.0"
short_array_element_width_threshold = 10
show_parse_errors = true
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
skip_children = false
skip_macro_invocations = []
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 20
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
style_edition = "2015"
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = false
wrap_comments = true
