[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.default]
clear = true
alias = "strip"

[tasks.build]
clear = true
dependencies = ["build-x64", "build-x86"]

[tasks.build-x86.linux]
clear = true
env = { "TARGET" = "i686-pc-windows-gnu" }
run_task = "build-common"

[tasks.build-x86.windows]
clear = true
env = { "TARGET" = "i686-pc-windows-msvc" }
run_task = "build-common"

[tasks.build-x64.linux]
clear = true
env = { "TARGET" = "x86_64-pc-windows-gnu" }
run_task = "build-common"

[tasks.build-x64.windows]
clear = true
env = { "TARGET" = "x86_64-pc-windows-msvc" }
run_task = "build-common"

[tasks.build-common.linux]
clear = true
script_runner = "@shell"
script = '''
echo "$ cargo build --release --target ${TARGET}"
cargo build --release --target ${TARGET}
'''
env = { "RUSTFLAGS" = "-C panic=abort -C link-arg=-Wl,--gc-sections -C link-arg=-Wl,--strip-all" }

[tasks.build-common.windows]
clear = true
script_runner = "@shell"
script = '''
echo "$ cargo build --release --target ${TARGET}"
cargo build --release --target ${TARGET}
'''
env = { "RUSTFLAGS" = "-C panic=abort -C link-arg=/SUBSYSTEM:console -C link-arg=/MERGE:.rdata=.text -C link-arg=/MERGE:.data=.text -C link-arg=/OPT:REF,ICF" }

[tasks.strip.linux]
clear = true
script_runner = "@shell"
script = '''
strip -s ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/i686-pc-windows-gnu/release/mod_coffee_core.dll
strip -s ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/x86_64-pc-windows-gnu/release/mod_coffee_core.dll
'''
dependencies = ["build"]

[tasks.strip.windows]
clear = true
run_task = "build"

